### ISSUE TITLE
can‘t exec CREATE TABLE

### ISSUE THREAD

**Issue by nqf** [RedBeardLab/rediSQL#108]
```
127.0.0.1:2009> REDISQL.EXEC DB "CREATE TABLE foo(A INT, B TEXT);"
(error) Command incomplete, no `COMMAND` nor `STATEMENT` fields
```

**Comment by siscia** [comment]
I guess you are running from master, correct?

You stumble upon the API v2.

Unfortunately I didn't document them yet.

You can still use the v1 API with a small change in the command:

```
REDISQL.V1.EXEC
```

This apply to all the commands, not only to EXEC, just prepend `V1`.

In alternative you can simply use the V2 API, you will need to look yourself into the code for the correct syntax until I don't document it, but the gigs for exec is.

```
REDISQL.EXEC DB COMMAND "you sql here"
```

Sorry about this, but I don't really got much time lately...

**Comment by nqf** [comment]
Thank you very much for your reply
