### ISSUE TITLE
Bulk insert

### ISSUE THREAD

**Issue by 979163895** [RedBeardLab/rediSQL#109]
Hello, I need a batch insert method?
Maybe a few hundred thousand, maybe more?
Thank you very much!

**Comment by siscia** [comment]
Hello,

are you a PRO costumer?

Can you please reach me privately with your license so we can discuss your use case?

Best Regards,
Simone

**Comment by 979163895** [comment]
Thank you, Simone. Besides this,

**Comment by siscia** [comment]
With the PRO version, you are buying my expertise.

There are way to make a batch insert, but it really depends on your architecture and use case.

Redis Cluster is already supported, but each database is a key, so you can have multiple databases clustered, but not different rows from the same database clustered. Does it make sense?

**Comment by 979163895** [comment]
Regarding "batch insert", if your way like this? 
    REDISQL.EXEC DB "INSERT INTO baz VALUES(3, 'ccc'),(4, 'ccc'),(5, 'ccc')......; 
Is there any way to make parallelism to further accelerate it?

**Comment by siscia** [comment]
Man there are a lot of way, which is best depends on your use case and architecture.

Feel free to study the documentation and the source code to understand what is best for your own use case.

Alternatively I am available for consultancy.

For quote and pricing feel free to reach me out at simone@redbeardlab.com

Closing now.
