### ISSUE TITLE
.NET Core Tutorial Request

### ISSUE THREAD

**Issue by snarlynarwhal** [RedBeardLab/rediSQL#111]
Hello, I would love to use RediSQL with C#/.NET Core.

**Comment by siscia** [comment]
I would love to help with this, but unfortunately I have zero experience in C# / .NET 

It should not be difficult to get started by yourself thought, you just need a way to send custom commands to redis that should already be implemented (maybe a little hidden) in most libraries.

**Comment by snarlynarwhal** [comment]
Ah, got it! Thank you. For anyone else that stumbles upon this: if you use [StackExchange.Redis](https://github.com/StackExchange/StackExchange.Redis), just use `db.Execute`.
