### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by Oah433** [RedBeardLab/rediSQL#117]
Hi
Fantastic module, but the documentation link seems to be broken.

**Comment by siscia** [comment]
Hello there!

Unfortunately I don't support anymore RediSQL.

We migrate to ZeeSQL.

Can you please refer to that one?

**Comment by siscia** [comment]
Anyway, what link is broken?

This seems to work fine:

https://redisql.redbeardlab.com/

**Comment by deefdragon** [comment]
its the link it jumpstart section, https://redisql.redbeardlab.com/rediSQL/blog/tutorial/

**Comment by siscia** [comment]
Yes this module is unmaintained.

Please refer to zeeSQL.com for the maintained version of the library.

Best regards
