### ISSUE TITLE
Failed to keep master and slave db in sync

### ISSUE THREAD

**Issue by jeffffrey** [RedBeardLab/rediSQL#18]
The setup is pretty simple : one instance running as master and the other running as slave. Use redis-cli to create a table on master , insert a few entries and try to read them from slave. To read data from slave, "slave-read-only" was set to "no". However, it seems the latest entries didn't sync from master to slave, and the only way to keep them in sync again is to restart the slave, which cause full sync. 

Note that AOF is disabled in both master and slave.

**Comment by siscia** [comment]
Hey @jeffffrey ,

I believe that you guys contacted me also via private email, is that correct?

Do you also have a test environemt where I can test the replication?

:)

**Comment by siscia** [comment]
Please, test this release one.

It is a trial, do not use in production.

[rediSQL_TRIAL_DO_NOT_USE_IN_PRODUCTION.so.zip](https://github.com/RedBeardLab/rediSQL/files/1386999/rediSQL_TRIAL_DO_NOT_USE_IN_PRODUCTION.so.zip)

**Comment by siscia** [comment]
Here is the 32 bit version.

[libredis_sql.so.zip](https://github.com/RedBeardLab/rediSQL/files/1388890/libredis_sql.so.zip)

**Comment by jeffffrey** [comment]
Hi Simone, sorry for late response. Yeah, I am working closely with Kevin, who contact you via separate channel. 

Built the code on 64bit env (glibc 2.17) and the replication issue seems resolved. Thanks.

**Comment by siscia** [comment]
Great!!!

Could you share how did you build it?
