### ISSUE TITLE
invoke from Java client 

### ISSUE THREAD

**Issue by neo-feng** [RedBeardLab/rediSQL#20]
Is it possible to use this from java client? I noticed the sample python code redis_pool.execute_command("REDISQL.EXEC", command), wondering if there is similar thing in java

**Comment by siscia** [comment]
Are you referring to jedis as java client?

We had a similar discussion on the issue #19 

If I find the time to test it I will write some documentation on using the modules on Jedis, feel free to contribute.

**Comment by neo-feng** [comment]
Thanks for your reply. I'm trying jedis and can create DB key successfuly now, but still cannot create table. I notice something strange, in your readme.md the statement is REDISQL.EXEC DB "CREATE TABLE foo(A INT, B TEXT);" while in the python script "redis_pool.execute_command("REDISQL.EXEC", command)", DB is missed. Shouldn't DB a required field?

**Comment by siscia** [comment]
Db is definitely a required fields. 

In the test is hidden in the context.  But you definitely need it! 

Usually is a great idea to use the redis-cli for exploring the module :)

**Comment by neo-feng** [comment]
Thanks for your reply, I'm trying jedis, I can successfully write data now using insert statement from jedis. Will try reading(select) tomorrow

**Comment by neo-feng** [comment]
hah, just noticed you replied my previous question, actually I figured it out later and got the write done, thanks anyway.

**Comment by siscia** [comment]
@neo-feng eventually we got a Java client!!!

You can find the client here:
https://github.com/RedBeardLab/JRediSQL

Cheers!

**Comment by neo-feng** [comment]
that is great, thanks for your notice, will try it on.
