### ISSUE TITLE
Error building rediSQL on raspberry pi

### ISSUE THREAD

**Issue by glenn-edgar** [RedBeardLab/rediSQL#23]
I received the following error log when trying to build rediSQL on raspberry pi.
Please let me know if I can supply further information

   Compiling rediSQL v0.3.0 (file:///home/pi/redis/modules/rediSQL-master)
libclang.solibclang.soerror: failed to run custom build command for `rediSQL v0.3.0 (file:///home/pi/redis/modules/rediSQL-master)`
process didn't exit successfully: `/home/pi/redis/modules/rediSQL-master/target/release/build/rediSQL-2d6d521084489aa0/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/CDeps
TARGET = Some("armv7-unknown-linux-gnueabihf")
OPT_LEVEL = Some("3")
TARGET = Some("armv7-unknown-linux-gnueabihf")
HOST = Some("armv7-unknown-linux-gnueabihf")
TARGET = Some("armv7-unknown-linux-gnueabihf")
TARGET = Some("armv7-unknown-linux-gnueabihf")
HOST = Some("armv7-unknown-linux-gnueabihf")
CC_armv7-unknown-linux-gnueabihf = None
CC_armv7_unknown_linux_gnueabihf = None
HOST_CC = None
CC = None
HOST = Some("armv7-unknown-linux-gnueabihf")
TARGET = Some("armv7-unknown-linux-gnueabihf")
HOST = Some("armv7-unknown-linux-gnueabihf")
CFLAGS_armv7-unknown-linux-gnueabihf = None
CFLAGS_armv7_unknown_linux_gnueabihf = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=armv7-a" "-I" "src/CDeps/Redis/include" "-Wall" "-Wextra" "-o" "/home/pi/redis/modules/rediSQL-master/target/release/build/rediSQL-f6317b3371ca522c/out/src/CDeps/Redis/redismodule.o" "-c" "src/CDeps/Redis/redismodule.c"
cargo:warning=src/CDeps/Redis/redismodule.c:3:25: warning: ‘DBType’ initialized and declared ‘extern’
cargo:warning= extern RedisModuleType *DBType = NULL;
cargo:warning=                         ^~~~~~
exit code: 0
TARGET = Some("armv7-unknown-linux-gnueabihf")
TARGET = Some("armv7-unknown-linux-gnueabihf")
HOST = Some("armv7-unknown-linux-gnueabihf")
AR_armv7-unknown-linux-gnueabihf = None
AR_armv7_unknown_linux_gnueabihf = None
HOST_AR = None
AR = None
TARGET = Some("armv7-unknown-linux-gnueabihf")
TARGET = Some("armv7-unknown-linux-gnueabihf")
running: "ar" "crs" "/home/pi/redis/modules/rediSQL-master/target/release/build/rediSQL-f6317b3371ca522c/out/libredismodule.a" "/home/pi/redis/modules/rediSQL-master/target/release/build/rediSQL-f6317b3371ca522c/out/src/CDeps/Redis/redismodule.o"
exit code: 0
TARGET = Some("armv7-unknown-linux-gnueabihf")
cargo:rustc-link-lib=static=redismodule
cargo:rustc-link-search=native=/home/pi/redis/modules/rediSQL-master/target/release/build/rediSQL-f6317b3371ca522c/out
TARGET = Some("armv7-unknown-linux-gnueabihf")
OPT_LEVEL = Some("3")
TARGET = Some("armv7-unknown-linux-gnueabihf")
HOST = Some("armv7-unknown-linux-gnueabihf")
TARGET = Some("armv7-unknown-linux-gnueabihf")
TARGET = Some("armv7-unknown-linux-gnueabihf")
HOST = Some("armv7-unknown-linux-gnueabihf")
CC_armv7-unknown-linux-gnueabihf = None
CC_armv7_unknown_linux_gnueabihf = None
HOST_CC = None
CC = None
HOST = Some("armv7-unknown-linux-gnueabihf")
TARGET = Some("armv7-unknown-linux-gnueabihf")
HOST = Some("armv7-unknown-linux-gnueabihf")
CFLAGS_armv7-unknown-linux-gnueabihf = None
CFLAGS_armv7_unknown_linux_gnueabihf = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=armv7-a" "-I" "src/CDeps/SQLite/include" "-Wall" "-Wextra" "-DHAVE_USLEEP=1" "-DNDEBUG=1" "-DHAVE_FDATASYNC=1" "-DSQLITE_THREADSAFE=1" "-DSQLITE_ENABLE_JSON1=1" "-DSQLITE_ENABLE_FTS3=1" "-DSQLITE_ENABLE_FTS4=1" "-DSQLITE_ENABLE_FTS5=1" "-DSQLITE_ENABLE_RTREE=1" "-o" "/home/pi/redis/modules/rediSQL-master/target/release/build/rediSQL-f6317b3371ca522c/out/src/CDeps/SQLite/sqlite3.o" "-c" "src/CDeps/SQLite/sqlite3.c"
exit code: 0
TARGET = Some("armv7-unknown-linux-gnueabihf")
TARGET = Some("armv7-unknown-linux-gnueabihf")
HOST = Some("armv7-unknown-linux-gnueabihf")
AR_armv7-unknown-linux-gnueabihf = None
AR_armv7_unknown_linux_gnueabihf = None
HOST_AR = None
AR = None
TARGET = Some("armv7-unknown-linux-gnueabihf")
TARGET = Some("armv7-unknown-linux-gnueabihf")
running: "ar" "crs" "/home/pi/redis/modules/rediSQL-master/target/release/build/rediSQL-f6317b3371ca522c/out/libsqlite3.a" "/home/pi/redis/modules/rediSQL-master/target/release/build/rediSQL-f6317b3371ca522c/out/src/CDeps/SQLite/sqlite3.o"
exit code: 0
TARGET = Some("armv7-unknown-linux-gnueabihf")
cargo:rustc-link-lib=static=sqlite3
cargo:rustc-link-search=native=/home/pi/redis/modules/rediSQL-master/target/release/build/rediSQL-f6317b3371ca522c/out

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any of [\'libclang.so\', \'libclang.so.*\'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (skipped: [])"', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by siscia** [comment]
Hi Glenn,

thank you for your report.

I cannot help you with your specific problem, the error just says that it was unable to find the libclang.so in your raspberry and to set the variable LIBCLANG_PATH to where that library is.

The code was not compatible with ARMv7, but thanks to your report, I spot the issues and fix it.

I release a new version v0.3.1 of the code, along with the binaries for both x64 and ARMv7.

If you want to run the code you could simply grab the binary and use it. [Here the link for ARMv7](https://github.com/RedBeardLab/rediSQL/releases/download/v0.3.1/libredis_sql_ARMv7.so)

Hope it helps you :)

**Comment by glenn-edgar** [comment]
I tried the library and it works on Raspberry pi

Thank you very much

**Comment by siscia** [comment]
Great! 

Thanks forse tour feedback! 

If fine any bugs or problems please let me know :)
