### ISSUE TITLE
`GLIBC_2.18' not found in CentOS 7

### ISSUE THREAD

**Issue by phuoc-huynh-ep** [RedBeardLab/rediSQL#26]
This error occurs when I load the rediSQL v0.3.1 module in CentOS 7. I try to find the issue on Google, but not working. If you have any idea, please help me. Thanks !
 `3116:M 24 Feb 10:10:34.237 # Module modules/libredis_sql.so failed to load: /lib64/libc.so.6: version 'GLIBC_2.18' not found (required by modules/libredis_sql.so)
3116:M 24 Feb 10:10:34.237 # Can't load module from modules/libredis_sql.so: server aborting
`

**Comment by siscia** [comment]
Hi, 

I start to believe that the lack of binaries for centos is a bigger problem that I thought. 

I will provide the binaries along with a way to build it by yourself. But it will take a while. 

Of course PR are welcome :)

**Comment by phuoc-huynh-ep** [comment]
Thank you for that! Could you show me the binaries and the way to build it? 

I have a hard time in few week ago so I'm late for reading your reply. Sorry about that.!

**Comment by siscia** [comment]
Hey @phuoc-huynh-ep ,

I just upload a new file under the release 0.3.1, the file is called `libredis_sql_LIBC2.17.so`, [here](https://github.com/RedBeardLab/rediSQL/releases/download/v0.3.1/libredis_sql_LIBC2.17.so) the direct link while [here](https://github.com/RedBeardLab/rediSQL/releases/tag/v0.3.1) the relase page.

Can you please let me know if this works for you?

Cheers,

**Comment by phuoc-huynh-ep** [comment]
It work well. Thank you very much !
