### ISSUE TITLE
PayHip hates me

### ISSUE THREAD

**Issue by salt4pommes** [RedBeardLab/rediSQL#37]
https://payhip.com/RediSQL

I am not able to buy the latest pro version.
Tried it yesterday and today and always get this error: "Apologies, could not complete transaction"

I can pay using my credit card at other payment providers, so my card is not the problem.

What can we do? :(

**Comment by siscia** [comment]
Hi,

Really sorry to hear about that.

I will follow up with then to understand what is the error and how it can be prevented for future times.

In the meantime I would suggest that we can go around the issue maybe with PayPal?

Would you be so kind to provide an email address that I can use to contact you?

You can write to simone@redbeardlab.tech so we can keep all the details privates and not on the public GitHub issue.

**Comment by salt4pommes** [comment]
I've send you an e-mail, so if you wish I could close the issue :)
