### ISSUE TITLE
'Use but do not abuse' unclear

### ISSUE THREAD

**Issue by drknexus** [RedBeardLab/rediSQL#4]
In the README you state "use but do not abuse" rediSQL.  However, I don't think it is entirely obvious what you mean by that.  Could you provide some clarification of what would count as use vs abuse?  Are the use cases that count as 'use' as broad as for SQLite in general or are there [use cases for SQLite](https://sqlite.org/whentouse.html) that you would consider abuse for rediSQL?

**Comment by siscia** [comment]
Hi,

sure, what I meant is that this is, in my opinion, a valid solution up to a certain level of complexity.

Then we would be better of using a more "classical" client-server DB.

Do you agree ?

Cheers,
Simone

**Comment by drknexus** [comment]
I think the unclear part is that you haven't quite staked out what 'certain level of complexity' means in your eyes.  It isn't that big a deal, but it would help readers know the scope of the project.  I think what you mean is entirely covered by the SQLite subheading: `Situations Where A Client/Server RDBMS May Work Better` on the link I provided in my original comment with the additional restriction that 'very large datasets' is probably generally well short of 140 TB.  

In practice is rediSQL limited to a single Redis key or are you doing some fancier stuff?  Clarifying on the size constraints alone would be a pretty big help.

I should have said it at the outset, but I'll say it now instead, thanks for opening up this pretty interesting project!

**Comment by siscia** [comment]
Hi @drknexus 

I do agree that a more precise description would help.

> I think the unclear part is that you haven't quite staked out what 'certain level of complexity' means in your eyes. 

A "certain level of complexity" does depends on the organization, clearly this answer doesn't help much.
I would personally start pretty much any project that need a database with SQLite and move from that one only when I really really need to. But if you need a lot of concurrent write, or you are handling huge dataset, maybe you could look elsewhere.

>  I think what you mean is entirely covered by the SQLite subheading

To point to the SQLite subheading is definitely a thing I will do and thanks for your suggestion.

> with the additional restriction that 'very large datasets' is probably generally well short of 140 TB.

The newer version of the module can save data on disk, so the dimension of the dataset is only limited by the internal of SQLite, which means 140TB. Of course if you are handling that many data maybe sqlite is not the best solution.

> In practice is rediSQL limited to a single Redis key or are you doing some fancier stuff?

I am not doing anything fancier than simply bound a redis key to a sqlite connection.

> I should have said it at the outset, but I'll say it now instead, thanks for opening up this pretty interesting project!

No, thank you for engaging this discussion with me, if you have any further question please let me know :)

**Comment by siscia** [comment]
Based on #8 I believe we may close the issue.

**Comment by drknexus** [comment]
Concur.  Thanks!
