### ISSUE TITLE
Is there a way to time a query?

### ISSUE THREAD

**Issue by invinciblycool** [RedBeardLab/rediSQL#40]
The redis logs give the time taken for the query execution but this time includes both the query translation of rediSQL and the actual database access time. Is there any way to just get the access time alone?

**Comment by siscia** [comment]
Hi,

At the moment there is not such interface.

What are you trying to achieve? Maybe there is a simpler way!

Cheers,

**Comment by invinciblycool** [comment]
I was trying to compare the time taken to execute a query between `sqlite` and `rediSQL` by performing the same query on the same data stored in sqlite and redis respectively. But since the SQL query is also translated while the query is performed, it surely adds to the total time.
Is there any way I could obtain the actual time taken for the database access?
Thanks.

**Comment by siscia** [comment]
I see!

No at the moment there is not such interface.

Indeed, RediSQL use SQLite under the hoo so the time performance should be roughly the same. There is of course some overhead in RediSQL but should barely be noticible for most use cases...

**Comment by siscia** [comment]
Please let me know if you got any further questions or of I should close the issue.
