### ISSUE TITLE
Provide a Ruby example using rediSQL 

### ISSUE THREAD

**Issue by martinstreicher** [RedBeardLab/rediSQL#48]
Ruby has at least one Redis gem. Provide an example to demonstrate how to use rediSQL with Ruby. Bonus: Show how something like `rake db:create db:migrate` might work.

**Comment by siscia** [comment]
That would be wonderful but I personally have zero experience in ruby.

If I try to make one, focusing on the RediSQL part, would you correct, enhance, fix the ruby part?

**Comment by martinstreicher** [comment]
I could try to make one with your guidance on the RediSQL parts, which likely are the same as the Python example. I’ll try to get to it this week.
