### ISSUE TITLE
Where is appropriate java client for rediSQL ?

### ISSUE THREAD

**Issue by walioul** [RedBeardLab/rediSQL#49]
Hello,

I want to make query like Standard SQL using java. Please make a tutorial for us using java. 

What dependencies are required to work properly like your python example using java please mention.

Thanks in advance.

**Comment by siscia** [comment]
Hi @walioul ,

I thought all day about this.

I am not able to create a tutorial in Java. I would start the tutorial by Googling "best java editor"... It is not going to fly.

However I am extremely commited to help you out at the best of my capabilities!

I can guide you through writing the tutorial yourself!

I will make sure that you get all the redis and RediSQL part right. I will explain to you the internals of RediSQL. I will do code review, suggestions, and even video call if necessary.

Moreover I will provide you a copy of RediSQL PRO.

I will suggest you to try!

Don't be scare it will work, if for any reason it doesn't work nobody will know!

Let me know if you are interested!

Cheers,
Simone

**Comment by siscia** [comment]
@walioul  I would suggest you to look into jedis-sql: https://github.com/xiao321/jedis-sql

**Comment by siscia** [comment]
@walioul 

We finally get a Java Client!

You can get it from here:
https://github.com/RedBeardLab/JRediSQL

I am also trying to publish it on Maven, but it take some time for that!
