### ISSUE TITLE
C++ Adaptor/ C++ API for Redis SQL.

### ISSUE THREAD

**Issue by codersguild** [RedBeardLab/rediSQL#54]
I can work on a C++ for Redis SQL inegration for exisiting C++ projects. I intend to use it in a blockchain implementation written in C++ primarily.

**Comment by siscia** [comment]
Hey there!

That is wonderful! 
If you need a copy of RediSQL PRO, feel free to reach by email: simone@redbeardlab.com

Moreover, if you have any question feel free to open issues or get on [gitter](https://gitter.im/rediSQL/community), whatever is more convenient for you!

Also, I am really looking for ergonomics feedback! Like it would be great if there was such and such function!

Looking forward to see your implementation!

**Comment by SpawnTree** [comment]
Thank you very much. I am still working on it. Let me get back whwn I am done. 

Thanks 
Sumit
