### ISSUE TITLE
Error: Version `GLIBC_2.25' not found in Ubuntu 16.04.2 LTS when load module

### ISSUE THREAD

**Issue by tungnt620** [RedBeardLab/rediSQL#60]
Hi guys, thanks guys for awsome Redis module.

I have tried to install with an environment like:
- RediSQL version 1.0.0 ( redisql_v1.0.0_x86_64.so )

- Redis server v=5.0.4 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=81f9a02b211fe0e1
- Ubuntu 16.04.2 LTS

And I have error:

> Module /etc/redis/redisql_v1.0.0_x86_64.so failed to load: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /etc/redis/redisql_v1.0.0_x86_64.so)
> Can't load module from /etc/redis/redisql_v1.0.0_x86_64.so: server aborting

I have checked and see the version of glibc in my server is: 

> apt-cache policy libc6
> libc6:
>   Installed: 2.23-0ubuntu11
>   Candidate: 2.23-0ubuntu11
>   Version table:
>  *** 2.23-0ubuntu11 500
>         500 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
>         100 /var/lib/dpkg/status
>      2.23-0ubuntu10 500
>         500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
>      2.23-0ubuntu3 500
>         500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages

I have tried with version redisql_v0.9.0_x86_64.so and it works like a champ

Can you help take a look? , thanks you.

**Comment by siscia** [comment]
Hi!

thanks!

I am going to release the version 1.0.1 soon. Hopefully today, likely on Tuesday.

I am going to include a version compiled with GLIBC 2.12 (for the curious compiled using the method explained in this blog post https://redbeardlab.com/2019/05/07/rust-and-glibc-version/)

There are not many functional differences between the 0.9 and the 1.0. 

The 0.9 does not includes the .NOW commands nor AOF, while the 1.0 include those but need telemetrics.

The 1.0.1 introduce minor bug fixes.

If you are in an hurry, you can compile it yourself, the difficult part is getting `bindgen` and its dependencies that anyway are in most package managers.

Alternatively, if you want to compile it yourself you can use the docker image in the blog post above. (git clone ...; cargo build)

Sorry for the rushed reply but I am traveling today.

**Comment by tungnt620** [comment]
Thank you for nice support.
I will wait for a new release. Now I will continue using version 0.9

**Comment by siscia** [comment]
Hi,

I just released the version 1.0.1

As always you can find it on the release part, on [payhip](https://payhip.com/RediSQL) and on [docker](https://hub.docker.com/r/siscia/redisql/tags)

Let me know if this works for you :)

Feel free to close the issue if it works for you!

Cheers,
Simone

**Comment by tungnt620** [comment]
Thank you. It works now 👍
