### ISSUE TITLE
how to get the  RediSQL .so file?

### ISSUE THREAD

**Issue by apple987** [RedBeardLab/rediSQL#63]
thanks a lot! this module is great! i want to learn it,but i don't know where to get  the  RediSQL .so file,need help !thanks !

**Comment by siscia** [comment]
Hi there!

you can either get it from Plasso https://payhip.com/b/8DId

or from github releases: https://github.com/RedBeardLab/rediSQL/releases

The PRO version without telemetrics in behind a paywall only on plasso: https://payhip.com/b/DvHg

Did it helps?

**Comment by apple987** [comment]
thanks a lot!
