### ISSUE TITLE
execute complicate sql to query stream data lead the database not work

### ISSUE THREAD

**Issue by xiao321** [RedBeardLab/rediSQL#66]
op_taxi_order have about 100k , and stream data write it continuely
op_taxi_order_all is small
when i run the sql , the result like this
> select a.car_no,a.city_id,a.city_name,(a.num+CASE WHEN b.total_num is null THEN 0 ELSE b.total_num END) total_num from (select car_no,city_id,city_name,count(1) num,sum(CASE WHEN call=0 THEN meterKm ELSE 0 END) meterKm,sum(CASE WHEN call=0 THEN emptyDrivingKm ELSE 0 END) emptyDrivingKm,sum(CASE WHEN call=1 THEN meterKm ELSE 0 END) call_meterKm,sum(CASE WHEN call=1 THEN emptyDrivingKm ELSE 0 END) call_emptyDrivingKm from op_taxi_order where time>'2019-06-17 00:00:00' and time<'2019-06-17 23:59:59' group by car_no,city_id,city_name) a left join op_taxi_order_all b on a.car_no=b.car_no limit 10
 > (nil)
 > (10.06s)
 > redisql.exec athenaT "SELECT * from op_status limit 10"
 > (nil)
 > (10.07s)

and the result of other sql  is wrong.
why? the athenaT  of database is locked? 
other database is good.  

how can i check the redisql log?

**Comment by siscia** [comment]
Hi,

from your description, I believe you are hitting a timeout.
RediSQL has a hardcoded timeout of 10 seconds, so if after 10 seconds the query didn't return it just abort the connection and returns (nil).

However, the query keeps going behind the scene, and I guess you hit a second timeout for your second query.

The timeout is extremely useful in development mode when I run the test, I believe that there is the need for a timeout also in production, but could be more than 10 seconds, like 60 seconds maybe?

It is the first time you try to do queries so big?
I will try to optimize the query if that is possible, do you have an index on the `time` column? Also one on `car_no` may help.

I reformatted the query to look like this:

``` sql
SELECT 
	a.car_no,a.city_id,a.city_name, (a.num+CASE WHEN b.total_num is null THEN 0 ELSE b.total_num END) total_num 
FROM 
	(SELECT car_no, city_id, city_name, count(1) num, 
		sum(CASE WHEN call=0 THEN meterKm ELSE 0 END) meterKm,
		sum(CASE WHEN call=0 THEN emptyDrivingKm ELSE 0 END) emptyDrivingKm,
		sum(CASE WHEN call=1 THEN meterKm ELSE 0 END) call_meterKm,
		sum(CASE WHEN call=1 THEN emptyDrivingKm ELSE 0 END) call_emptyDrivingKm 
	FROM op_taxi_order 
		WHERE 
			time>'2019-06-17 00:00:00' AND -- <-- an index here may help
			time<'2019-06-17 23:59:59' 
		GROUP BY car_no,city_id,city_name) a 
LEFT JOIN op_taxi_order_all b ON a.car_no=b.car_no 
LIMIT 10
```
It seems an analytic queries that does not need to run very quickly.
A solution would be to export the data into a file-backed SQLite database and then run then query in the background. Let me know if you need help in doing so.

The logs for redisql are enabled on the debug mode, but they slow down quite a bit the whole thing and are on STDOUT. At the moment they are mostly for debugging, not operations.

It is something that you need? I can add those if necessary.

Cheers,
Simone

**Comment by xiao321** [comment]
i open the redis debug mode, but log info is little. i can not analyse the reason by it.
need your help to add more info.

**Comment by xiao321** [comment]
> Hi,
> 
> from your description, I believe you are hitting a timeout.
> RediSQL has a hardcoded timeout of 10 seconds, so if after 10 seconds the query didn't return it just abort the connection and returns (nil).
> 
> However, the query keeps going behind the scene, and I guess you hit a second timeout for your second query.
> 
> The timeout is extremely useful in development mode when I run the test, I believe that there is the need for a timeout also in production, but could be more than 10 seconds, like 60 seconds maybe?
> 
> It is the first time you try to do queries so big?
> I will try to optimize the query if that is possible, do you have an index on the `time` column? Also one on `car_no` may help.
> 
> I reformatted the query to look like this:
> 
> ```sql
> SELECT 
> 	a.car_no,a.city_id,a.city_name, (a.num+CASE WHEN b.total_num is null THEN 0 ELSE b.total_num END) total_num 
> FROM 
> 	(SELECT car_no, city_id, city_name, count(1) num, 
> 		sum(CASE WHEN call=0 THEN meterKm ELSE 0 END) meterKm,
> 		sum(CASE WHEN call=0 THEN emptyDrivingKm ELSE 0 END) emptyDrivingKm,
> 		sum(CASE WHEN call=1 THEN meterKm ELSE 0 END) call_meterKm,
> 		sum(CASE WHEN call=1 THEN emptyDrivingKm ELSE 0 END) call_emptyDrivingKm 
> 	FROM op_taxi_order 
> 		WHERE 
> 			time>'2019-06-17 00:00:00' AND -- <-- an index here may help
> 			time<'2019-06-17 23:59:59' 
> 		GROUP BY car_no,city_id,city_name) a 
> LEFT JOIN op_taxi_order_all b ON a.car_no=b.car_no 
> LIMIT 10
> ```
> 
> It seems an analytic queries that does not need to run very quickly.
> A solution would be to export the data into a file-backed SQLite database and then run then query in the background. Let me know if you need help in doing so.
> 
> The logs for redisql are enabled on the debug mode, but they slow down quite a bit the whole thing and are on STDOUT. At the moment they are mostly for debugging, not operations.
> 
> It is something that you need? I can add those if necessary.
> 
> Cheers,
> Simone

i open the redis debug mode, but log info is little. i can not analyse the reason by it.
need your help to add more info.

**Comment by siscia** [comment]
Can you recompile the software yourself?

It is sufficient to recompile it without the --release flag.

Then you will have A LOT of logs!

You need me to provide a debug release?

**Comment by xiao321** [comment]
now we have no the env to recompile it. then if you convenient，provide me a debug release. thanks very much @siscia

**Comment by siscia** [comment]
Hi there,

a debug build is here: https://github.com/RedBeardLab/rediSQL/releases/download/v1.0.2/libredisql_v1.0.2_debug.so

Let me know if it works on your environment, please also consider that it will be quite slower and it will produce a lot of logs.

Cheers,
Simone

**Comment by siscia** [comment]
Did it helps? Any updates?

**Comment by xiao321** [comment]
> Did it helps? Any updates?

the env is not yet right. after i test it, i will give you feedback.

now i feel confused, i put 300k data into redis by redisql，but only use 2.5M memory.
`> redisql.exec athenaT "select count(1) from order"
1) 1) (integer) 2192968
> redisql.exec athenaT "select count(1) from status"
1) 1) (integer) 8811
> redisql.exec athenaT "select count(1) from status_his"
1) 1) (integer) 1144453
> info memory
# Memory
used_memory:2663328
used_memory_human:2.54M
used_memory_rss:889516032
used_memory_rss_human:848.31M
used_memory_peak:78446072
used_memory_peak_human:74.81M
used_memory_peak_perc:3.40%
`
why? some data in the disk?

**Comment by xiao321** [comment]
this is test result.
{code}
[2019-06-27T09:52:24Z DEBUG redis_sql::commands] Exec | GotDB
[2019-06-27T09:52:24Z DEBUG redis_sql::commands] Exec | BlockedClient
[2019-06-27T09:52:24Z DEBUG redis_sql::commands] Exec | Create Command
[2019-06-27T09:52:24Z DEBUG redisql_lib::redis] Exec | Query = "replace into op_driver(driver_id,device_id,cert_id,car_no,company_id,city_id) values(\'1011\',\'300455245\',\'\u{90}ÖG\u{0}d\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{3}G\',\'陕AT10000\',\'-1\',\'16\')"
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NulError(124, [114, 101, 112, 108, 97, 99, 101, 32, 105, 110, 116, 111, 32, 111, 112, 95, 100, 114, 105, 118, 101, 114, 40, 100, 114, 105, 118, 101, 114, 95, 105, 100, 44, 100, 101, 118, 105, 99, 101, 95, 105, 100, 44, 99, 101, 114, 116, 95, 105, 100, 44, 99, 97, 114, 95, 110, 111, 44, 99, 111, 109, 112, 97, 110, 121, 95, 105, 100, 44, 99, 105, 116, 121, 95, 105, 100, 41, 32, 118, 97, 108, 117, 101, 115, 40, 39, 54, 49, 48, 52, 50, 54, 49, 57, 56, 49, 48, 57, 50, 49, 51, 57, 49, 49, 39, 44, 39, 51, 48, 48, 52, 53, 53, 50, 52, 53, 39, 44, 39, 194, 144, 195, 150, 71, 0, 100, 0, 0, 0, 0, 0, 0, 0, 3, 71, 39, 44, 39, 233, 153, 149, 65, 84, 49, 57, 51, 50, 39, 44, 39, 45, 49, 39, 44, 39, 49, 54, 39, 41])', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[2019-06-27T09:52:24Z DEBUG redisql_lib::redis_type] Free thread safe context
[2019-06-27T09:52:24Z DEBUG redisql_lib::redis] RedisContextSet | Drop
[2019-06-27T09:52:24Z DEBUG redisql_lib::redis] ### Dropping Loop ###

{code}

**Comment by siscia** [comment]
Don't be confused.

Unfortunately RediSQL does not use the standard Redis allocator, so the result from `INFO MEMORY` does not take into account the data in RediSQL.

I did a lot of work to try to incorporate the two, but without much success.

Are those information useful? I could expose these two interfaces:

1. https://www.sqlite.org/c3ref/db_status.html
2. https://www.sqlite.org/c3ref/status.html

**Comment by siscia** [comment]
For what concern the error, what `replace into` should do?

Definitely should not crash, I agree, but I  am not sure this is doing what you think is doing. Honestly this `replace` syntax is new to me.

**Comment by xiao321** [comment]
i use insert  into , the result is same.

**Comment by siscia** [comment]
Alright, I see the problem!

Your query contains `NULL` characters! Are you sure this is something you want?

**Comment by siscia** [comment]
So the `cert_id` I believe contains NULL, while RediSQL parse the string and it founds a NULL characters and it crash because it does not expect NULL inside a query.

Does it crash also if you use statements?

**Comment by xiao321** [comment]
yes the cert_id contains dirty data. 
but when i put it into redis, the database shutdown. 
i must reboot the redis.

**Comment by siscia** [comment]
Indeed, in general, it is a problem because Redis is based on a text protocol, and using NULL in a text protocol is not ideal.

Give me a little bit of time and let see if I can come up with something!

**Comment by xiao321** [comment]
> For what concern the error, what `replace into` should do?
> 
> Definitely should not crash, I agree, but I am not sure this is doing what you think is doing. Honestly this `replace` syntax is new to me.

The idea of the REPLACE statement is that when a UNIQUE or PRIMARY KEY constraint violation occurs, the REPLACE statement:

First, delete the existing row that causes the constraint violation.
Second, insert a new row.

http://www.sqlitetutorial.net/sqlite-replace-statement/

**Comment by siscia** [comment]
With some degree of confidence the error is here: https://github.com/RedBeardLab/rediSQL/blob/master/redisql_lib/src/community_statement.rs#L71

**Comment by xiao321** [comment]
> With some degree of confidence the error is here: https://github.com/RedBeardLab/rediSQL/blob/master/redisql_lib/src/community_statement.rs#L71

i think it is bug, can you resolve it?

**Comment by siscia** [comment]
Hi there,

yes it is going to be fixed, but how?

I believe that SQLite does not accept strings with null values in, for good reason also.

**Comment by siscia** [comment]
Also, what command to you execute to have NULL characters inside the query?

**Comment by xiao321** [comment]
> Also, what command to you execute to have NULL characters inside the query?

create table op_driver(driver_id text,device_id text,cert_id text,car_no text,company_id text,city_id text,PRIMARY KEY(driver_id,device_id))

insert into op_driver(driver_id,device_id,cert_id,car_no,company_id,city_id) values('1011','300455245','ÖG d       G','陕AT10000','-1','16')

**Comment by siscia** [comment]
Hey there,

Looking again at the query, it seems quite unreasonable to expect that such query goes through fine.

I believe there is some encoding missmatch between the data you send to RediSQL and what you wrote here.

I still believe that RediSQL should refuse the query and return an error for this. Do you agree?

Also, did you guys tried to encode the certificate in base64? It should still be univocal and much more friendly for any database! Is that possible for your use case?

Before to write much code, I really want your feedback guys because you both showed several times to be good engineers, so if you believe that queries like these should go through just fine maybe I am missing something.

Honestly I have no idea how to pass such string to SQLite, but again I might miss something.

**Comment by xiao321** [comment]
yes , i agree your point. RediSQL should refuse the query and return an error for this.
this is my expect.  According to the valid error info,  i can use the base64 to process it. this is a good way.

but now i can not get the valid error on my client. and it leads to the database not work.

**Comment by siscia** [comment]
Deal!

I will proceed to make these changes and release a new version hopefully today!

:)

**Comment by xiao321** [comment]
> Deal!
> 
> I will proceed to make these changes and release a new version hopefully today!
> 
> :)

thanks ! ^~^

Another scenario , the database will be not work too.  not return the valid error on my client.

i have a table with 400k data . Then execute the sql to delete 100K data, like this
"delete from A where day > '2018-06-29 00:00:00' and day < '2019-06-29 00:00:00' ".

**Comment by siscia** [comment]
Does this timeout?

I need to fix the timeout as well.

What I believe happens, is that the query takes more than 10sec, RediSQL timeout, and it replies to you with an empty response. However, eventually the query terminates, and it tried to reply, but the internal state is "corrupted" by the previous timeouted reply, so the thread crash. Only the thread crash so RediSQL keep running and you just see something that stop working.

Can you confirm this with the debug build? Just post the logs if you can reproduce it.

**Comment by xiao321** [comment]
> Does this timeout?
> 
> I need to fix the timeout as well.
> 
> What I believe happens, is that the query takes more than 10sec, RediSQL timeout, and it replies to you with an empty response. However, eventually the query terminates, and it tried to reply, but the internal state is "corrupted" by the previous timeouted reply, so the thread crash. Only the thread crash so RediSQL keep running and you just see something that stop working.
> 
> Can you confirm this with the debug build? Just post the logs if you can reproduce it.

yes, i think you are right. after i test it on debug mode, i will post more info.

**Comment by siscia** [comment]
Hi,

do you guys have a test for this NULL-bytes in command bug?

I am not quite sure how to replicate it.

Anyhow, can you please test this RC: https://github.com/RedBeardLab/rediSQL/releases/download/v1.0.3-rc01/libredis_sql.so

Cheers,
Simone

**Comment by xiao321** [comment]
after i write the data, the database also not work. you can try it.

this is my test code:
BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream("E://sql.txt")));
 jedis.executeSQL("test", "create table op_driver(driver_id text,device_id text,cert_id text,car_no text,company_id text,city_id text,PRIMARY KEY(driver_id,device_id))");
jedis.executeSQL("test", br.readLine());

sql.txt 
`insert into op_driver(driver_id,device_id,cert_id,car_no,company_id,city_id) values('1011','300455245','ÖG d       G','陕AT10000','-1','16')`

this is my test result. my client get the error 
`redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
	at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:205)
	at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:43)
	at redis.clients.jedis.Protocol.process(Protocol.java:154)
	at redis.clients.jedis.Protocol.read(Protocol.java:219)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:313)
	at redis.clients.jedis.Connection.getRawObjectMultiBulkReply(Connection.java:280)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:284)
	at redis.clients.jedis.Jedis.executeSQL(Jedis.java:3661)
	at test.DemoApplication.writeRideDataToRedis(DemoApplication.java:58)
	at test.DemoApplication.run(DemoApplication.java:184)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:797)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.didachuxing.bigdata.redis.sql.DemoApplication.main(DemoApplication.java:26)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:199)
	... 15 more`

the redis log:
`thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NulError(124, [114, 101, 112, 108, 97, 99, 101, 32, 105, 110, 116, 111, 32, 111, 112, 95, 100, 114, 105, 118, 101, 114, 40, 100, 114, 105, 118, 101, 114, 95, 105, 100, 44, 100, 101, 118, 105, 99, 101, 95, 105, 100, 44, 99, 101, 114, 116, 95, 105, 100, 44, 99, 97, 114, 95, 110, 111, 44, 99, 111, 109, 112, 97, 110, 121, 95, 105, 100, 44, 99, 105, 116, 121, 95, 105, 100, 41, 32, 118, 97, 108, 117, 101, 115, 40, 39, 54, 49, 48, 52, 50, 54, 49, 57, 56, 49, 48, 57, 50, 49, 51, 57, 49, 49, 39, 44, 39, 51, 48, 48, 52, 53, 53, 50, 52, 53, 39, 44, 39, 194, 144, 195, 150, 71, 0, 100, 0, 0, 0, 0, 0, 0, 0, 3, 71, 39, 44, 39, 233, 153, 149, 65, 84, 49, 57, 51, 50, 39, 44, 39, 45, 49, 39, 44, 39, 49, 54, 39, 41])', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.`

**Comment by xiao321** [comment]
> Does this timeout?
> 
> I need to fix the timeout as well.
> 
> What I believe happens, is that the query takes more than 10sec, RediSQL timeout, and it replies to you with an empty response. However, eventually the query terminates, and it tried to reply, but the internal state is "corrupted" by the previous timeouted reply, so the thread crash. Only the thread crash so RediSQL keep running and you just see something that stop working.
> 
> Can you confirm this with the debug build? Just post the logs if you can reproduce it.

i test this on two scenarios.
a table with 400k data，execute the command "delete from a where id>2000000 and id<3000000", then my client get the error " read timeout".  but the database can work, only "10s" timeout
redis log:

[2019-07-02T07:35:44Z DEBUG redisql_lib::redis] Exec | Query = "delete from a where id>2000000 and id<3000000"
[2019-07-02T07:35:44Z DEBUG redisql_lib::redis] do_execute | created statement
[2019-07-02T07:35:44Z DEBUG redisql_lib::community_statement] Execute | Acquired db lock
[2019-07-02T07:35:44Z DEBUG redisql_lib::community_statement] Execute | Read row modified before
[2019-07-02T07:35:54Z DEBUG redisql_lib::sqlite] FromIterator => DONECursor
[2019-07-02T07:35:54Z DEBUG redisql_lib::community_statement] Execute=> Executed trains of statements
[2019-07-02T07:35:54Z DEBUG redisql_lib::community_statement] Execute=>DONECursor
[2019-07-02T07:35:54Z DEBUG redisql_lib::redis] do_execute | statement executed
[2019-07-02T07:35:54Z DEBUG redisql_lib::redis_type] Free thread safe context
[2019-07-02T07:35:54Z DEBUG redisql_lib::redis] RedisContextSet | Drop
[2019-07-02T07:35:54Z DEBUG redisql_lib::redis] with_contex_set | exit
[2019-07-02T07:35:54Z DEBUG redisql_lib::redis] Exec | DONE, returning result
[2019-07-02T07:35:54Z DEBUG redisql_lib::redis] Loop iteration


another : 
a table with 400k data , when i execute the command "delete from b where id>1000000 and id<2000000", the streaming data always write into the table.
my client get the error " timeout". **but the database can not work.**

the redis log:
[2019-07-02T08:55:17Z DEBUG redisql_lib::redis] Exec | Query = "delete from b where id>=1000000 and id<2000000"
[2019-07-02T08:55:17Z DEBUG redisql_lib::redis] do_execute | created statement
[2019-07-02T08:55:17Z DEBUG redisql_lib::community_statement] Execute | Acquired db lock
[2019-07-02T08:55:17Z DEBUG redisql_lib::community_statement] Execute | Read row modified before
[2019-07-02T08:55:17Z DEBUG redis_sql::commands] Exec | GotDB
[2019-07-02T08:55:17Z DEBUG redis_sql::commands] Exec | BlockedClient
[2019-07-02T08:55:17Z DEBUG redis_sql::commands] Exec | Create Command
[2019-07-02T08:55:28Z DEBUG redis_sql::commands] Exec | GotDB
[2019-07-02T08:55:28Z DEBUG redis_sql::commands] Exec | BlockedClient
[2019-07-02T08:55:28Z DEBUG redis_sql::commands] Exec | Create Command
[2019-07-02T08:55:28Z DEBUG redisql_lib::sqlite] FromIterator => DONECursor
[2019-07-02T08:55:28Z DEBUG redisql_lib::community_statement] Execute=> Executed trains of statements
[2019-07-02T08:55:28Z DEBUG redisql_lib::community_statement] Execute=>DONECursor
[2019-07-02T08:55:28Z DEBUG redisql_lib::redis] do_execute | statement executed
[2019-07-02T08:55:28Z DEBUG redisql_lib::redis_type] Free thread safe context
[2019-07-02T08:55:28Z DEBUG redisql_lib::redis] RedisContextSet | Drop
[2019-07-02T08:55:28Z DEBUG redisql_lib::redis] with_contex_set | exit
[2019-07-02T08:55:28Z DEBUG redisql_lib::redis] Exec | DONE, returning result
[2019-07-02T08:55:28Z DEBUG redisql_lib::redis] Loop iteration

why? lock compete lead to?

**Comment by siscia** [comment]
Wait, lets keep the two issues separated.

I need to find a way to test, the NULL issue.

For the lock issue, please open a new github issue and let's keep the discussion there!

**Comment by xiao321** [comment]
ok

**Comment by siscia** [comment]
Thanks!

In the meantime, do you mind to try the rc02?

You can find here both the debug and the release builds: https://github.com/RedBeardLab/rediSQL/releases/tag/v1.0.3-rc02

Many thanks!

**Comment by xiao321** [comment]
i test v1.0.3. it is ok. thanks 
👍 
my client return 
redis.clients.jedis.exceptions.JedisDataException: ERR - Error Code: -13796096 => Trying to create a statement with a NULL byte. | ERR - Error Code: 999 => Find NULL byte in position 124 while trying to create a statement | Trying to create a statement with a NULL byte.

**Comment by siscia** [comment]
Wonderful!

Let me work on the other issues now! :)
