### ISSUE TITLE
Real-time streaming data is frequently written to redisql tables by multiple threads, making the entire library unavailable

### ISSUE THREAD

**Issue by baochengjie** [RedBeardLab/rediSQL#67]
Wonder if the database is locked? Restart after recovery, how to solve, log debug did not make a mistake

**Comment by siscia** [comment]
Hi!

is that related to #66 ?

What is happening?

It is an emergency or a general question?

What is your setup? Are you memory based or disk-based? What the machine is doing (look into htop)?

I can help but I need to understand the situation clearly.

**Comment by baochengjie** [comment]
yes!

I just thought that sql is too complicated, which caused the database to be unavailable, but after the timeout was found, even the normal select * could not be executed.

**Comment by baochengjie** [comment]
Streaming redisql.exec to change table data
for example replace into table values(?,?,?)

**Comment by siscia** [comment]
Is RediSQL doing some work?
You can look it up using htop.

Honestly what happens after a timeout is not well tested, can you turn it off and restart it?

**Comment by baochengjie** [comment]
ok！
Flink streaming write redisql,which will update the data in the table frequently.
RediSQL does some simple analysis
I can't login to the server now.
Recovered after restart,but this problem will still occur when writing data to redisql.

**Comment by baochengjie** [comment]
> Is RediSQL doing some work?
> You can look it up using htop.
> 
> Honestly what happens after a timeout is not well tested, can you turn it off and restart it?

I found this problem, I don't know if it is a bug, sending data to the server is garbled, redisql will crash the entire database.

Table statement：
create table op_driver(driver_id text,device_id text,cert_id text,car_no text,company_id text,city_id text,PRIMARY KEY(driver_id,device_id))

sql图:

![image](https://user-images.githubusercontent.com/33924130/59915252-c8478100-944e-11e9-9786-e28557f1a6e9.png)

**Comment by baochengjie** [comment]
> Is RediSQL doing some work?
> You can look it up using htop.
> 
> Honestly what happens after a timeout is not well tested, can you turn it off and restart it?

I found this problem, I don't know if it is a bug, sending data to the server is garbled, redisql will crash the entire database.

Table statement：
create table op_driver(driver_id text,device_id text,cert_id text,car_no text,company_id text,city_id text,PRIMARY KEY(driver_id,device_id))

sql图:

![image](https://user-images.githubusercontent.com/33924130/59915427-31c78f80-944f-11e9-8fc0-33ca2bb34af0.png)
@siscia

**Comment by siscia** [comment]
Does it give you some error?

The query: `replace into` is unknow to me.

Maybe are trying to do an insert? or an update?

Also I shared a debug releases here: https://github.com/RedBeardLab/rediSQL/releases/download/v1.0.2/libredisql_v1.0.2_debug.so (it needs a quite new version of glibc)

Does that helps?

**Comment by baochengjie** [comment]
I will try it

**Comment by siscia** [comment]
Any updates?

**Comment by baochengjie** [comment]
that  is related to #66 
close
