### ISSUE TITLE
need client and demo for java

### ISSUE THREAD

**Issue by apple987** [RedBeardLab/rediSQL#68]
This is a great project. So far, I have seen several other language clients. When can the author produce the Java version of the client? There is no enough demonstration examples. Finally, I hope the project will get better and better!

**Comment by siscia** [comment]
Hi there,

java is always been an issue.

Unfortunately I don't have the experience to build a client for it.

However there is an attempt here: https://github.com/xiao321/jedis-sql

Sorry!

**Comment by siscia** [comment]
Alright, we do have a client for Java! :rocket: 

https://github.com/RedBeardLab/JRediSQL

I am trying to publish it to Maven, but it takes some time.

Please, close this issue if this is satisfactory for you!

Cheers,
Simone
