### ISSUE TITLE
When there are multiple hash prefixes in redis, such as cat: 1, cat: 2,... Dog: 1 dog: 2..., the virtual table does not work properly.

### ISSUE THREAD

**Issue by CSNight** [RedBeardLab/rediSQL#75]
Do the following:
1.Create 100 hashtable  key with 'cats' prefix to write  in redis and then write 100 hashtable key with 'dogs' prefix
2. Run command **REDISQL.CREATE_DB DB**
3.  Run command **REDISQL.EXEC DB "CREATE VIRTUAL TABLE funny_cats USING REDISQL_TABLES_BRUTE_HASH(cats, name, location, hungry);"** 
4. Run command **REDISQL.EXEC DB "SELECT COUNT(*) FROM funny_cats"**
the result constantly not equals 100.
I don't know it has been designed to not support to build virtual table when redis has mutil key prefix or a mistake.
I didn't find a solution in the instructions on the official website, so I hope to get your help.

**Comment by siscia** [comment]
Hi,

what do you get? Also dogs? Or less cats?

Do you have a script so I can reproduce it quickly?

**Comment by CSNight** [comment]
`    public static void tests() {
        //Get a Redis connection from pool
        MultiRedisConnPoolST st = MultiRedisConnPoolST.getInstance();
        String guid = GUID.getUUID();
        JediSQL jediSQL = st.getJedis(guid);
        //clear db
        jediSQL.flushAll();
        //create a test field 
        Map<String, String> field = new HashMap<>();
        field.put("DSDS", "AAA");
        //create three table name prefix
        String table1 = "dogs";
        String table2 = "cats";
        String table3 = "cows";
        // insert 100 hash table into redis table name such as "cats:132131"
        for (int i = 0; i < 100; i++) {
            jediSQL.hmset(table1 + ":" + getRandomNum(6), field);
        }
        //create a db by redisql
        jediSQL.create_db("DB");
        //create a virtual table cats
        jediSQL.exec("DB", "CREATE VIRTUAL TABLE " + table1 + " USING REDISQL_TABLES_BRUTE_HASH(" + table1 + ",DSDS);");
        // insert another 100 hash table into redis table name such as "dogs:132131"
        for (int i = 0; i < 100; i++) {
            jediSQL.hmset(table2 + ":" + getRandomNum(6), field);
        }
        // insert another 100 hash table into redis table name such as "cows:132131"
        for (int i = 0; i < 100; i++) {
            jediSQL.hmset(table3 + ":" + getRandomNum(6), field);
        }
        //search cats virtual table by sql clause  REDISQL.EXEC "SELECT COUNT(*) FROM cats" and print the result
        System.out.println(jediSQL.exec("DB", "SELECT COUNT(*) FROM " + table1).get(0));
        //close redis connection
        st.close(guid);
    }`
This is wirte by java ,i hope you can understand.
I have run the code ten times ,the print result should be 100 always , but is print like the blow
[100]
[100]
[100]
[41]
[100]
[100]
[41]
[4]
[6]
[100]

**Comment by siscia** [comment]
I see and it is definitely a problem/bug!

Thanks for reporting it.

The usual steps are:
    1. Write some test and make sure that they fail
    2. Fix it

However, what is your use case for this?

The point is that those virtual tables are quite complex to maintain inside the code-base and I am thinking about dropping them.

So, at this point, we have two alternatives. 
1. Drop the virtual table from redisql
2. Keep them paying the price

I want to understand how you are using them.

**Comment by CSNight** [comment]
Hi,
We using the virtual table to statistic thousands of  hashtable by sql clause in redis.

These hashtables are continuously written into redis,  every five seconds, writing about 10,000 items.

In the cycle,after written hashtables completed, we build virtual table, then run sql to statistic keys in virtual table.

Because of this bug ,we have to delete hashtables of previous cycle in every cycle, because the redisql seems don't allow table prefix more than 1. This can take a lot of time, and a lot of write and delete operations can lead to database instability. (sometimes redis fails)

I have test directly use the redisql insert command to insert records instead of creating virtual tables through hashtable, but it seems that the insert command not fast enough to meet our needs.

In addition, my customers are likely to be reluctant to pay the price. ╮(╯_╰)╭

So, I recommend providing a new API to enable redisql to support batch insertion of records, similar to redis pipeline, and to improve insertion efficiency. Also this must support multiple tables coexisting at the same time.

Of course, we would be very grateful if you can fix this problem, because this progrom is about to go online.

**Comment by CSNight** [comment]
**//create a db by redisql**
        jediSQL.create_db("DB");
        jediSQL.exec("DB", "CREATE TABLE cats(key TEXT, DSDS TEXT)");
        long start = System.currentTimeMillis();
        **// insert 8000 hash table into redis table name such as "cats:132131"**
        for (int i = 0; i < 8000; i++) {
            jediSQL.exec("DB", "INSERT INTO cats VALUES('cats:" + i + "','AAA')");
        }
        long end_insert = System.currentTimeMillis();
        System.out.println("Use insert command:" + (end_insert - start) + "ms");
        **//use pipeline hmset**
        Pipeline pipe = jediSQL.pipelined();
        for (int i = 0; i < 8000; i++) {
            pipe.hmset("cat:" + i, field);
        }
        pipe.sync();
        long end_pipe = System.currentTimeMillis();
        System.out.println("Use insert command:" + (end_pipe - end_insert) + "ms");

result print:
Use insert command: 5121ms
Use pipeline: 46ms

**Comment by siscia** [comment]
Hi there,

It should definitely not use 5 seconds to insert 8k records.

Did you try to use the pipeline also for RediSQL commands? There is a reason why you don't use the pipeline with RediSQL?

Also, to get more performance, especially in cases like this one, it is a good idea to use statements.

Finally, last trick, is to write all of those in a single transaction.

So you open the pipeline, execute 'BEGIN;' then the 8k statements and finally you execute 'COMMIT;' and finally you flush the pipeline.

**Comment by siscia** [comment]
Also, consider using multiple connections!

**Comment by siscia** [comment]
The honest reality is that hashtables virtual table are a little bit of an hack and there are definitely rough edges around them.

**Comment by CSNight** [comment]
Can you give me an example about single transaction with statements? 
And to use pipeline i have to edit the source code of jedis to make it support pipe

**Comment by siscia** [comment]
That's why I hate Jedis! You are right about the pipeline.

Also the use of statement won't help much, you will still be waiting for the network after each command.

The simplest solution that I see is to open multiple connections each one in a thread, and each one of them inserting stuff. I understand is suboptimal but it is likely the fastest way.

The cleanest way would be to add pipeline support to jedisql, I will offer a free Pro version of RediSQL to whoever will do it.

**Comment by CSNight** [comment]
Thanks a lot ,i already made  the jedis to support redisql but still try to make it support redisql on pipeline.
The code is in my github,named JediSQL. 
If i can make it support pipeline, i will commit the code.

**Comment by siscia** [comment]
Aw I thought you were using mine!

https://github.com/RedBeardLab/JRediSQL

**Comment by CSNight** [comment]
emmm...,
In fact, I learned from yours and[ jedis-sql](https://github.com/xiao321/jedis-sql) to enable redisql to support clustering and use redisql like simple jedis function like the code i show you, instead of build a outside custom client

**Comment by CSNight** [comment]
now  it can support pipeline now 
[JediSQL](https://github.com/CSNight/JediSQL)

**Comment by siscia** [comment]
That's wonderful!

How are the performance?

How difficult would it be to get the code inside JRediSQL?

**Comment by CSNight** [comment]
It took 2s to insert 8k records by pipeline, not as fast as I imagined.A lot of time was spent on "sync" function. Maybe  more fast if we can optimize the "sync" function or use statements and transaction,but i don't have time to test these now.

If you want to get the code inside JRediSQL, you may have to override the class about pipeline in jedis such as **PipelineBase,Pipeline, BuilderFactory** and so on,then make your client class to inherit the override custom pipeline class.
This won't be difficult but it may cost time to understand the relationship between many interfaces and classes and override them.

**Comment by CSNight** [comment]
```
        //Get a Redis connection from pool
        MultiRedisConnPoolST st = MultiRedisConnPoolST.getInstance();
        String guid = GUID.getUUID();
        JediSQL jediSQL = st.getJedis(guid);
        //clear db
        jediSQL.flushAll();
        //use pipeline
        Pipeline pipe = jediSQL.pipelined();
        //create a db by redisql
        Response<String> rs1 = pipe.create_db("DB");
        pipe.sync();
        System.out.println(rs1.get());
        //create a table by redisql
        Response<List<Object>> rs2 = pipe.exec("DB", "CREATE TABLE cats(key TEXT, DSDS TEXT)");
        pipe.sync();
        System.out.println(rs2.get());
        long start = System.currentTimeMillis();
        pipe.create_statement_now("DB", "st", "INSERT INTO cats VALUES(?1,?2)");
        pipe.sync();
        // insert 8000 hash table into redis table name such as "cats:132131"
        for (int i = 0; i < 8000; i++) {
            pipe.exec_statement_now("DB", "st", "cats:" + i, "AAA");
        }
        pipe.sync();
        long sync_insert = System.currentTimeMillis();
        System.out.println("Use insert command:" + (sync_insert - start) + "ms");
        st.close(guid);
```
print result:
```
OK
[DONE]
Use insert command:75ms
```
The results with **statements and pipeline** are very good, guaranteeing that the insertion time is at the millisecond level.
