### ISSUE TITLE
Drop virtual table

### ISSUE THREAD

**Issue by siscia** [RedBeardLab/rediSQL#76]
Hi all, 

I am thinking about dropping the virtual table from RediSQL, the one that are created with `REDISQL_TABLES_BRUTE_HASH`.

They are quite complex to maintain, and they don't bring too many benefits I believe.

Is somebody using them? How?

Somebody want to really keep them around?

At the beginning of August (2 weeks from now), if nobody complained, I will decide to drop those virtual table.

**Comment by CSNight** [comment]
It is useful when someone don't want to rewrite the records in redis by redisql , especially the number of records is very large. Remove this api means this people should write another db to run sql to protect the source data.

So, how about just keep it,if this doesn't affect any other APIs a lot

**Comment by siscia** [comment]
I believe we are able to keep virtual tables!

**Comment by siscia** [comment]
Unfortunately I wasn't able to retain virtual tables.

See #84 

Still have to merge them, are there people actually using them?

**Comment by siscia** [comment]
Before to actually drop them, I want to make sure that we will gain the expected capabilities of having multiple readers.
