### ISSUE TITLE
May I ask how sqlite3 is being used in this project? 

### ISSUE THREAD

**Issue by the-oaks** [RedBeardLab/rediSQL#80]
look like this project is tagged sqlite3, may I ask how sqlite3 is being used in this project? thanks

**Comment by siscia** [comment]
Hi!

Sure you may ask! :)

SQLite is the main SQL engine behind RediSQL, all the SQL is executed by SQLite.
You got a new query, the query is sent over the SQLite engine, the engine execute it, returns the result and you got the result back.

For sake of completeness, Redis, handle all the connection/platform deals.
So the connection, replication, persistence is provided by Redis.

Does this help? 

Cheers,
Simone

**Comment by the-oaks** [comment]
understood, so one of the key benefits of using redisql is to allow multiple application querying the same data set - comparing to a naive in-memory version sqlite? I assume redisql will be slower than sqlite-inmemory though, given there might be overhead on the serialization/deserialization?

**Comment by siscia** [comment]
Yes, in general it will be slower than raw SQLite.

And yes the use case is indeed to provide a fast in memory SQL engine that speak with the network.

**Comment by siscia** [comment]
Please, if you have other question feel free to open the issue again!
