### ISSUE TITLE
Steps to build rediSQL from source in centos 7

### ISSUE THREAD

**Issue by shannonantony** [RedBeardLab/rediSQL#82]
Please provide steps to install rediSQL from source under Centos 7.

thanks

jaison

**Comment by siscia** [comment]
Hi!

It requires to have a working version of bindgen ( https://github.com/rust-lang/rust-bindgen/blob/master/README.md )

That as you can see, requires few packages to be installed in the system: https://rust-lang.github.io/rust-bindgen/requirements.html

If I remember correctly there was several issues with Centos7 , I would suggest to you a more modern system altogether if it is possible.

(Honestly can't wait for Centos8!)
