### ISSUE TITLE
rediSQL 1.1.2 crashed after insert 30000000 data

### ISSUE THREAD

**Issue by catchex** [RedBeardLab/rediSQL#86]
------ STACK TRACE ------
EIP:
0   redis-server                        0x000000010ca4172e RM_GetThreadSafeContext + 206

Backtrace:
0   redis-server                        0x000000010ca0c8de logStackTrace + 110
1   redis-server                        0x000000010ca0ccad sigsegvHandler + 253
2   libsystem_platform.dylib            0x00007fff7143ab5d _sigtramp + 29
3   ???                                 0x00007fba86c474e1 0x0 + 140439101666529
4   libredis_sql.dylib                  0x000000010ce98518 _ZN11redisql_lib10redis_type7Context11thread_safe17h173587aec900936fE + 24
5   libredis_sql.dylib                  0x000000010cc0ec20 _ZN11redisql_lib5redis12return_value17h8eb3fcc5ed17fb52E + 48
6   libredis_sql.dylib                  0x000000010cc0f9d2 _ZN11redisql_lib5redis18listen_and_execute17h7c893ecfc6c5d1e8E + 2274
7   libredis_sql.dylib                  0x000000010cc0d4ea _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17h36b1ce80d340c846E.llvm.1591913181271004175 + 74
8   libredis_sql.dylib                  0x000000010cc17f50 _ZN3std9panicking3try7do_call17h8497b91ada36b121E.llvm.4219096736137588322 + 64
9   libredis_sql.dylib                  0x000000010d047a3f __rust_maybe_catch_panic + 31
10  libredis_sql.dylib                  0x000000010cc19cb7 _ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17haec6bce7634e4ee6E + 151
11  libredis_sql.dylib                  0x000000010d043eae _ZN83_$LT$alloc..boxed..Box$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$9call_once17h0c87090ae5188728E + 62
12  libredis_sql.dylib                  0x000000010d04553e _ZN3std10sys_common6thread12start_thread17hb442747e0ab69dd0E + 142
13  libredis_sql.dylib                  0x000000010d0448f9 _ZN3std3sys4unix6thread6Thread3new12thread_start17h7e0ebc55f14d4c40E + 9
14  libsystem_pthread.dylib             0x00007fff714432eb _pthread_body + 126
15  libsystem_pthread.dylib             0x00007fff71446249 _pthread_start + 66
16  libsystem_pthread.dylib             0x00007fff7144240d thread_start + 13

**Comment by siscia** [comment]
Azz I am sorry!

Can you reproduce? Does it happen every time?

Could it be an out of memory? Does not seems like, but worth making sure.

It is exactly 30.000.000 rows or is around that amount of rows?

Were you using virtual tables?

**Comment by catchex** [comment]
crashed randomly, it happens at 17800000,  72000000 rows,  the max 3.8G memory is consumed

**Comment by siscia** [comment]
What query are you executing?

**Comment by catchex** [comment]
group by key or select something

**Comment by siscia** [comment]
Hummm, it is not helping honestly.

Are you using virtual tables in RediSQL? If not, do you mind to try the latest RC candidate?
https://github.com/RedBeardLab/rediSQL/releases/tag/v%232.0.0-rc02
