### ISSUE TITLE
Do you have PHP 7 example of working with RediSQL?

### ISSUE THREAD

**Issue by DesRodman** [RedBeardLab/rediSQL#89]
Hello team
At your main site - i can see info about PHP examples and link to this repo, but here i can find it

Can you please share to me example of PHP 7+ ?

Thanks

**Comment by siscia** [comment]
Hi!

Unfortunately we are not really experts in PHP, so it is a little hard for us to produce good material on it.

What library are you using for talking with redis? A reasonable guess would be [phpredis](https://github.com/phpredis/phpredis), in that case I will look into the [`rawCommand` method](https://github.com/phpredis/phpredis/blob/develop/README.markdown#rawcommand).

Let me know if you have any trouble!
