### ISSUE TITLE
32bit build

### ISSUE THREAD

**Issue by lefedor** [RedBeardLab/rediSQL#93]
Hello, can You please make 32 bit build release?
Need to scale solution fir the old system.

**Comment by siscia** [comment]
Arm or x86_64?

**Comment by lefedor** [comment]
x86_32

**Comment by siscia** [comment]
Yeah right, i686

**Comment by siscia** [comment]
So, I have no way to test this, so you need to try it and tell me if it is working.


[RediSQL.zip](https://github.com/RedBeardLab/rediSQL/files/4112168/RediSQL.zip)

**Comment by siscia** [comment]
Also, this is build from master, you most likely need a build from some specific tag/version.

Let me know :)

**Comment by siscia** [comment]
For reference: https://github.com/alexcrichton/cc-rs/issues/469

**Comment by siscia** [comment]
Did it work?

**Comment by lefedor** [comment]
Hello, want report my cacher database works fine at i686 build, if has all features required.

**Comment by siscia** [comment]
Wonderful!

I will close the issue.

If you enjoy this project would be great if you could support it.

The classic way would be to buy a license for the pro version. Another great option would be to write/blog about your project and mention RediSQL! I will make sure to share the content as much as possible in my small circle.

Anyway I am glad it worked for you! 
Cheers
