### ISSUE TITLE
Can this be compiled to web assembly ?

### ISSUE THREAD

**Issue by imanghafoori1** [RedBeardLab/rediSQL#94]
Can this be compiled to web assembly (or wasi) and use the local storage to persist data? or maybe ignore persistence feature all together for web assembly version.

**Comment by siscia** [comment]
Hummm, maybe, in theory, idk...

But why? Whatare you trying to achieve?

I believe that with enough effort you could produce a web assembly binary, but I am not sure it would be a good idea.

Care to elaborate more?

**Comment by imanghafoori1** [comment]
I think it would be nice to have an sql database on the client side, for offline ready progressive web apps. (the same as android applications can work offline and interact with a local sqlite on mobile devices.)
It's just some imaginations, I am not an expert in PWAs.

**Comment by imanghafoori1** [comment]
Also, WASI provides light wight sand boxing, it is web assembly out side browser. (like nodejs is javascript out side browser.)
Maybe the sandboxing feature of wasi is needed by some folks.

**Comment by siscia** [comment]
In those case I would try to compile directly SQLite, but I believe that there are already attempts for this.

Anyhow, RediSQL is based on SQLite.

If I answered your question please feel free to close the issue.
