### ISSUE TITLE
RediSQL in .net core

### ISSUE THREAD

**Issue by han2291** [RedBeardLab/rediSQL#95]
Hello, 
I would like to connect RediSQL with .net core . Please make a tutorial for us using .net core.

**Comment by siscia** [comment]
Hi There,

I would love it, but I have zero experience with .NET

What I can do is to help you as much as possible, should we do it?

What library are you using to connect to redis?

Cheers,
Simone

**Comment by gkorland** [comment]
@han2291 did you try to use https://github.com/StackExchange/StackExchange.Redis?

**Comment by han2291** [comment]
In fact I have already tried using the StackEschange.Redis library and my code is as follows:

`RedisCacheService redisCache = new RedisCacheService(ConnectionMultiplexer.Connect("localhost:6379"));
redisCache.SetCacheValueAsync("test", "Hello world");`

The ConnectionMulteplexer class (this class is from StackEschange.Redis) is used to connect to Redis and in the Connect method it is assigned the ip with the connection port to RediSQL but when executing this method, the following exception appears:

StackExchange.Redis.RedisConnectionException: 'It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING'

I have already tested this same code with the base version of Redis and it works.
Note: The RedisCacheService object encapsulates calls to StackEschange.Redis
`public class RedisCacheService : ICacheService
{

        private readonly IConnectionMultiplexer _connectionMultiplexer;
        public RedisCacheService(IConnectionMultiplexer connectionMultiplexer)
        {
            _connectionMultiplexer = connectionMultiplexer;
        }

        public async Task SetCacheValueAsync(string key, string value)
        {
            var db = _connectionMultiplexer.GetDatabase();
            await db.StringSetAsync(key, value);
        }
    }
`

**Comment by siscia** [comment]
Hummm, it seems mostly an issue of your setup honestly.

Can you share the log of redis?
